webui/forms.py
from flask_wtf import FlaskForm
from flask_wtf.file import FileField, FileRequired, FileAllowed
from wtforms import StringField, SubmitField
from wtforms.validators import DataRequired
from webui.extensions import cts

class CTForm(FlaskForm):
    case  = StringField(u'病歷號', validators=[DataRequired()], render_kw={'placeholder': u'病歷號', 'class': 'w-75'})
    ct = FileField(validators=[FileAllowed(cts, u'只能上傳圖片!'), FileRequired(u'請選擇圖片')], render_kw={'style': 'display:none'})
    submit = SubmitField(u'上傳', render_kw={'class': 'btn btn-jelly normal-btn loading'})

webui/__init__.py
import os
from flask import Flask, render_template
from flask_uploads import configure_uploads

from webui.setting import config
from webui.blueprints.webui import webui_bp
from webui.extensions import cts


def create_app(config_name=None):
    if config_name is None:
        config_name = os.getenv('FLASK_CONFIG', 'development')

    app = Flask('webui')
    app.config.from_object(config[config_name])

    app.jinja_env.trim_blocks = True
    app.jinja_env.lstrip_blocks = True

    register_extensions(app)
    register_blueprints(app)
    register_errors(app)
    return app


def register_extensions(app):
    # upload config
    configure_uploads(app, cts)


def register_blueprints(app):
    app.register_blueprint(webui_bp)


def register_errors(app):
    # invalid route
    @app.errorhandler(404)
    def page_not_found(e):
        return render_template('error.html', error=['Page Not Found', '此頁面不存在']), 404

    # server error
    @app.errorhandler(500)
    def internal_server_error(e):
        return render_template('error.html', error=['Internal Server Error', '伺服器發生錯誤']), 500

webui/blueprints/webui.py
import os
import gc
from datetime import datetime
from subprocess import Popen
import multiprocessing as mp
import time
from flask import Blueprint, render_template, request, redirect, url_for, flash, current_app, jsonify, Response

from webui.extensions import cts

from webui.forms import CTForm


webui_bp = Blueprint('webui', __name__)


def getFiles(path=None):
    files = os.listdir(path)
    files = [list(os.path.splitext(file))+[datetime.fromtimestamp(os.path.getctime(os.path.join(path, file))).strftime("%Y/%m/%d - %H:%M:%S")] for file in files]
    files.sort(key = lambda files: files[2])
    return files


def getAbsPath(path=None):
    basedir = os.path.abspath(os.path.dirname(os.path.dirname(__file__)))
    path = os.path.join(basedir, path)
    return path



@webui_bp.route('/', methods=('GET', 'POST'))
def index():
    form = CTForm()

    if request.method == 'POST':
        current_datetime = datetime.now().strftime('%Y-%m-%d_%H-%M-%S')

        for filename in request.files.getlist('ct'):
            cts.save(filename, folder=current_datetime)

        # Set args
        source = os.path.join(current_app.config['UPLOADED_CTS_DEST'], current_datetime)
        dest = os.path.join(current_app.config['UPLOADED_CTS_DEST'], current_datetime, 'heatmap.gif')
        y_weight = getAbsPath('../checkpoints/yolov5_512_500.pt')
        c_weight = getAbsPath('../checkpoints/3dcnn_d64.h5')

        p = Popen('python ../predict.py -i {} -o {} -yw {} -cw {} -c {}'.format(source, dest, y_weight, c_weight, request.form.get('case')), shell=True)
        p.wait()

        return url_for('static', filename='cts/{}/heatmap.gif'.format(current_datetime))
    return render_template('index.html', form=form, postURL=url_for('webui.index'), filesURL=url_for('webui.files'))



@webui_bp.route('/about', methods=('GET', 'POST'))
def about():
    return render_template('about.html')


@webui_bp.route('/files', methods=('GET', 'POST'))
def files():
    path = current_app.config['UPLOADED_CTS_DEST']
    path = getAbsPath(path)
    folders = sorted(os.listdir(path))
    folders.reverse()

    urls = [url_for('static', filename='cts/{}/heatmap.gif'.format(folder)) for folder in folders]
    cases = []
    prs = []

    for folder in folders:
        txt_path = os.path.join(path, folder, 'result.txt')
        with open(txt_path, 'r') as f:
            lines = f.readlines()
            cases.append(lines[0].strip())
            prs.append(lines[1].strip())
    
    return render_template('files.html', folders=folders, urls=urls, cases=cases, prs=prs)


@webui_bp.route('/cxr', methods=('GET', 'POST'))
def cxr():
    form = CTForm()
    print(cxr)
    if request.method == 'POST':
        current_datetime = datetime.now().strftime('%Y-%m-%d_%H-%M-%S')

        filepath = ""
        new_folder = ""
        for file in request.files.getlist('ct'):
            
            # 創建一個帶有當前日期和時間的新資料夾
            new_folder = os.path.join("/home/weiyu110/stroke-prediction/webui/static/cxrs", current_datetime)
            os.makedirs(new_folder, exist_ok=True)
            
            # 保存圖片到新建的資料夾中
            filepath = os.path.join(new_folder, file.filename)
            file.save(filepath)

        # Set args
        source = filepath
        dest = new_folder

        p = Popen('python /home/weiyu110/Joe_paper/predict_cxr.py -i {} -o {} -c {}'.format(source,dest, request.form.get('case')), shell=True)
        p.wait()

        # return url_for('static', filename='cts/{}/heatmap.gif'.format(current_datetime))
        return "success"
    return render_template('cxr.html', form=form, postURL=url_for('webui.cxr'), filesURL=url_for('webui.files_cxr'))


@webui_bp.route('/files_cxr', methods=('GET', 'POST'))
def files_cxr():

    path = "/home/weiyu110/stroke-prediction/webui/static/cxrs"
    folders = sorted(os.listdir(path))
    folders.reverse()

    urls = [url_for('static', filename='cxrs/{}/crop_image.png'.format(folder)) for folder in folders]
    cases = []
    prs = []

    for folder in folders:
        txt_path = os.path.join(path, folder, 'prediction_result.txt')
        with open(txt_path, 'r') as f:
            lines = f.readlines()
            cases.append(lines[0].strip())
            prs.append(lines[1].strip())
    
    return render_template('files.html', folders=folders, urls=urls, cases=cases, prs=prs)

webui/templates/_modal.html
<div class="modal fade bd-example-modal-lg" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <div class="embed-responsive embed-responsive-16by9">
        <h2 class="text-center"></h2>
        <img src="" class="rounded mx-auto d-block" alt="">
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal" id="save-range">確認</button>
      </div>
    </div>
  </div>
</div>

webui/templates/_site-section.html
<div class="site-section">
  <div class="container">
    <div class="row">
      <div class="col-lg-6">
        <div class="section-title">
          <h2>選擇檔案</h2>
        </div>
        <div class="post-entry-2 d-flex col" style="margin-bottom:1em ">
          <div class="thumbnail">
            <img src="{{ url_for('static', filename='images/upload.png') }}" alt="Example" width="30%" height="30%"
              style="display: block; margin: auto;margin-top: 20%; width: 18%; height: 30%;">

          </div>
          <div class="contents">
            <p class="mb-3">選擇這部電腦上的檔案進行分析</p>
            <div class="col">
              <div class="row" style="margin-bottom:1em;">
                <div class="col-3 text-center"
                  style="background: rgb(248, 248, 248); font-weight: 500; color:rgb(60, 60, 60); letter-spacing: 2px;">
                  檔案</div>
                <div id="file-name" class="col-9"
                  style="color: gray ; border: 0.5px 0.5px 0.5px 0 rgb(248,248,248) solid;">尚未選擇</div>
              </div>
            </div>


          </div>
        </div>
        <div class="col">
          <form method="POST" enctype="multipart/form-data">
            {{ form.hidden_tag() }}
            <div class="row justify-content-md-center">
              <div class="col-3">
                {{ form.case }}
              </div>
              <div class="col-3">
                <label class="btn btn-jelly normal-btn">
                  {{ form.ct(multiple="multiple") }}
                  <span>選擇圖片</span>
                </label>
              </div>
              <div class="col-3">
                <label class="btn btn-jelly normal-btn" id="select-range" data-toggle="modal" data-target=".bd-example-modal-lg">
                  <span>範圍</span>
                </label>
              </div>
              <div class="col-3">
                {{ form.submit }}
              </div>
            </div>
          </form>
        </div>
      </div>
      <div class="col-lg-6">
        <div class="section-title">
          <h2>瀏覽結果</h2>
        </div>
        <div class="post-entry-2 d-flex">
          <div class="thumbnail">
            <img src="{{ url_for('static', filename='images/search.png') }}" alt="Example" width="30%" height="30%"
              style="display: block; margin: auto;margin-top: 20%; width: 18%; height: 30%;">

          </div>
          <div class="contents">
            <p class="mb-3">觀看分析完成的成果</p>
            <h2><a class="btn btn-jelly normal-btn" href="{{ filesURL }}" style="color: white;">點此瀏覽</a></h2>

          </div>
        </div>
      </div>
    </div>
  </div>
</div>

{% include '_modal.html' %}

{% block javascript %}
<script>
  $('#ct').parent().click(function () {
    $('#ct').change(function () {
      $('#view-result').fadeOut();
      $('.md-auto').removeClass('flow-bg-active').addClass('flow-bg').find('p').removeClass('flow-text-active').addClass('flow-text')
      $('.step-two').removeClass('spinner-border spinner-border-sm').text('❷');

      $('.md-auto').eq(0).removeClass('flow-bg').addClass('flow-bg-active')
        .find('p').removeClass('flow-text').addClass('flow-text-active')

      filename = $(this)[0].files.length + ' 個檔案'

      if (filename != '') {
        $('#file-name').text(filename)
      }
      else {
        $('#file-name').text('尚未選擇')
      }
    })
  })

  input = document.getElementById('ct')

  // 範圍
  $('#select-range').click(function () {
    $('.embed-responsive').empty()
    obj = '<br><div class="row justify-content-md-center"><div class="col"><img src="" class="rounded mx-auto d-block start" alt=""></div><div class="col"><img src="" class="rounded mx-auto d-block end" alt=""></div></div>' 
    $('.embed-responsive').append(obj)
    $('.embed-responsive img').attr({'style': 'width:300px; height:300px'})
    

    reader1 = new FileReader()
    reader1.onload = function(e) {
      $('.start').attr('src', e.target.result);
    }
    reader1.readAsDataURL(input.files[0])

    reader2 = new FileReader()
    reader2.onload = function(e) {
      $('.end').attr('src', e.target.result);
    }
    reader2.readAsDataURL(input.files[input.files.length - 1])

    obj = $('<br><div id="slider" style="width: 90%; margin-left: auto; margin-right: auto;"></div><br>')

    start = 1
    end = input.files.length

    slider = obj.slider({
      range: true,
      min: 1,
      max: input.files.length,
      values: [1, input.files.length],
      slide: function(event, ui) {
        file1 = input.files[ui.values[0]]
        file2 = input.files[ui.values[1]]
        reader1.readAsDataURL(file1)
        reader2.readAsDataURL(file2)
        start = ui.values[0]
        end = ui.values[1]
      }
    })

    btn = document.getElementById('save-range');
    btn.addEventListener('click', function(e){
      dt = new DataTransfer()
      for(i = start -1; i < end; i++) {
        dt.items.add(input.files[i])
      }
      input.files = dt.files
      filename = input.files.length + ' 個檔案'
      $('#file-name').text(filename)
    });

    $('.embed-responsive').append(slider)
  })

  $('form').submit(function (e) {
    e.preventDefault()
    data = new FormData($('form')[0])
    $.ajax({
      type: 'POST',
      url: '{{ postURL }}',
      data: data,
      contentType: false,
      cache: false,
      processData: false,
      beforeSend: function () {
        $('.md-auto').removeClass('flow-bg-active').addClass('flow-bg')
          .find('p').removeClass('flow-text-active').addClass('flow-text')
        $('.md-auto').eq(1).removeClass('flow-bg').addClass('flow-bg-active').find('p').removeClass('flow-text').addClass('flow-text-active')
        $('.step-two').text('').addClass('spinner-border spinner-border-sm');
      },
      success: function (msg) {
        $('.md-auto').removeClass('flow-bg-active').addClass('flow-bg')
          .find('p').removeClass('flow-text-active').addClass('flow-text')
        $('.step-two').removeClass('spinner-border spinner-border-sm').text('❷');

        // $('#view-result').fadeIn();
        $('.md-auto').eq(2).removeClass('flow-bg').addClass('flow-bg-active')
          .find('p').removeClass('flow-text').addClass('flow-text-active')

        $('.modal img').attr({ 'src': msg })
      }
    })
  })
</script>
{% endblock %}

webui/templates/_site-section_cxr.html
<div class="site-section">
  <div class="container">
    <div class="row">
      <div class="col-lg-6">
        <div class="section-title">
          <h2>選擇檔案</h2>
        </div>
        <div class="post-entry-2 d-flex col" style="margin-bottom:1em ">
          <div class="thumbnail">
            <img src="{{ url_for('static', filename='images/upload.png') }}" alt="Example" width="30%" height="30%"
              style="display: block; margin: auto;margin-top: 20%; width: 18%; height: 30%;">

          </div>
          <div class="contents">
            <p class="mb-3">選擇這部電腦上的檔案進行分析</p>
            <div class="col">
              <div class="row" style="margin-bottom:1em;">
                <div class="col-3 text-center"
                  style="background: rgb(248, 248, 248); font-weight: 500; color:rgb(60, 60, 60); letter-spacing: 2px;">
                  檔案</div>
                <div id="file-name" class="col-9"
                  style="color: gray ; border: 0.5px 0.5px 0.5px 0 rgb(248,248,248) solid;">尚未選擇</div>
              </div>
            </div>


          </div>
        </div>
        <div class="col">
          <form method="POST" enctype="multipart/form-data">
            {{ form.hidden_tag() }}
            <div class="row justify-content-md-center">
              <div class="col-3">
                {{ form.case }}
              </div>
              <div class="col-3">
                <label class="btn btn-jelly normal-btn">
                  {{ form.ct }}
                  <span>選擇圖片</span>
                </label>
              </div>
              <!-- <div class="col-3">
                <label class="btn btn-jelly normal-btn" id="select-range" data-toggle="modal" data-target=".bd-example-modal-lg">
                  <span>範圍</span>
                </label>
              </div> -->
              <div class="col-3">
                {{ form.submit }}
              </div>
            </div>
          </form>
        </div>
      </div>
      <div class="col-lg-6">
        <div class="section-title">
          <h2>瀏覽結果</h2>
        </div>
        <div class="post-entry-2 d-flex">
          <div class="thumbnail">
            <img src="{{ url_for('static', filename='images/search.png') }}" alt="Example" width="30%" height="30%"
              style="display: block; margin: auto;margin-top: 20%; width: 18%; height: 30%;">

          </div>
          <div class="contents">
            <p class="mb-3">觀看分析完成的成果</p>
            <h2><a class="btn btn-jelly normal-btn" href="{{ filesURL }}" style="color: white;">點此瀏覽</a></h2>

          </div>
        </div>
      </div>
    </div>
  </div>
</div>

{% include '_modal.html' %}

{% block javascript %}
<script>
  $('#ct').parent().click(function () {
    $('#ct').change(function () {
      $('#view-result').fadeOut();
      $('.md-auto').removeClass('flow-bg-active').addClass('flow-bg').find('p').removeClass('flow-text-active').addClass('flow-text')
      $('.step-two').removeClass('spinner-border spinner-border-sm').text('❷');

      $('.md-auto').eq(0).removeClass('flow-bg').addClass('flow-bg-active')
        .find('p').removeClass('flow-text').addClass('flow-text-active')

      filename = $(this)[0].files.length + ' 個檔案'

      if (filename != '') {
        $('#file-name').text(filename)
      }
      else {
        $('#file-name').text('尚未選擇')
      }
    })
  })

  input = document.getElementById('ct')

  // 範圍
  $('#select-range').click(function () {
    $('.embed-responsive').empty()
    obj = '<br><div class="row justify-content-md-center"><div class="col"><img src="" class="rounded mx-auto d-block start" alt=""></div><div class="col"><img src="" class="rounded mx-auto d-block end" alt=""></div></div>' 
    $('.embed-responsive').append(obj)
    $('.embed-responsive img').attr({'style': 'width:300px; height:300px'})
    

    reader1 = new FileReader()
    reader1.onload = function(e) {
      $('.start').attr('src', e.target.result);
    }
    reader1.readAsDataURL(input.files[0])

    reader2 = new FileReader()
    reader2.onload = function(e) {
      $('.end').attr('src', e.target.result);
    }
    reader2.readAsDataURL(input.files[input.files.length - 1])

    obj = $('<br><div id="slider" style="width: 90%; margin-left: auto; margin-right: auto;"></div><br>')

    start = 1
    end = input.files.length

    slider = obj.slider({
      range: true,
      min: 1,
      max: input.files.length,
      values: [1, input.files.length],
      slide: function(event, ui) {
        file1 = input.files[ui.values[0]]
        file2 = input.files[ui.values[1]]
        reader1.readAsDataURL(file1)
        reader2.readAsDataURL(file2)
        start = ui.values[0]
        end = ui.values[1]
      }
    })

    btn = document.getElementById('save-range');
    btn.addEventListener('click', function(e){
      dt = new DataTransfer()
      for(i = start -1; i < end; i++) {
        dt.items.add(input.files[i])
      }
      input.files = dt.files
      filename = input.files.length + ' 個檔案'
      $('#file-name').text(filename)
    });

    $('.embed-responsive').append(slider)
  })

  $('form').submit(function (e) {
    e.preventDefault()
    data = new FormData($('form')[0])
    $.ajax({
      type: 'POST',
      url: '{{ postURL }}',
      data: data,
      contentType: false,
      cache: false,
      processData: false,
      beforeSend: function () {
        $('.md-auto').removeClass('flow-bg-active').addClass('flow-bg')
          .find('p').removeClass('flow-text-active').addClass('flow-text')
        $('.md-auto').eq(1).removeClass('flow-bg').addClass('flow-bg-active').find('p').removeClass('flow-text').addClass('flow-text-active')
        $('.step-two').text('').addClass('spinner-border spinner-border-sm');
      },
      success: function (msg) {
        $('.md-auto').removeClass('flow-bg-active').addClass('flow-bg')
          .find('p').removeClass('flow-text-active').addClass('flow-text')
        $('.step-two').removeClass('spinner-border spinner-border-sm').text('❷');

        // $('#view-result').fadeIn();
        $('.md-auto').eq(2).removeClass('flow-bg').addClass('flow-bg-active')
          .find('p').removeClass('flow-text').addClass('flow-text-active')

        $('.modal img').attr({ 'src': msg })
      }
    })
  })
</script>
{% endblock %}

webui/templates/_step.html
<div class="col" style="margin-top: 4em;">
  <div class="row">
    <div class="col md-auto flow-bg-active">
      <p class="text-center flow-text-active">❶ 選擇圖片</p>
    </div>
    <div class="col md-auto flow-bg">
      <p class="text-center flow-text"><span class="step-two">❷</span> 分析中</p>
    </div>
    <div class="col md-auto flow-bg">
      <p class="text-center flow-text">❸ 分析完成</p>
    </div>
  </div>
  <div id="view-result" class="col" style="margin-top: 1em;">
    <p class="mb-3 text-center" style="font-weight: 500;">點擊下方按鈕觀看</p>
    <div class="row justify-content-md-center">
      <div class="col col-3 flow-play">
        <a href="#" data-toggle="modal" data-target=".bd-example-modal-lg">
          <p class="text-center flow-text" style="color: white;">➤ 觀看結果</p>
        </a>
      </div>
    </div>
  </div>

</div>

webui/templates/about.html
{% extends 'base.html' %}

{% block content %}
<div class="py-0">
  <div class="container">
    <div class="half-post-entry d-block d-lg-flex bg-light">
      <div class="contents col-8">
        <span class="caption">Members</span>
        <h2 style="color:rgb(20, 20, 20)">研究成員</h2>

      </div>

    </div>
    <div class="col" style="margin-top: 2em;">
      <div class="trend-entry d-flex">
        <div class="number align-self-start" style="color: #FF7C83;font-weight: 400;">01</div>
        <div class="trend-contents col">
          <div class="col">
            <h2 style="color: rgb(30, 30, 30)">呂 政修</h2>
            <div class="post-meta">
            </div>
          </div>

          <hr style="margin: 10px 0;">
          <div class="col">
            <span class="d-block">國立台灣科技大學電子工程系 教授兼主任秘書</span>
          </div>
        </div>
      </div>
      <div class="trend-entry d-flex">
        <div class="number align-self-start" style="color: #FF516B;font-weight: 400;">02</div>
        <div class="trend-contents col">
          <div class="col">
            <h2 style="color: rgb(30, 30, 30) ;">蔡 佳醍</h2>
            <div class="post-meta">
            </div>
          </div>

          <hr style="margin: 10px 0;">
          <div class="col">
            <span class="d-block">國立台灣大學醫學院內科 專任教授</span>
          </div>
        </div>
      </div>
      <div class="trend-entry d-flex">
        <div class="number align-self-start" style="color: #FF7C83;font-weight: 400;">03</div>
        <div class="trend-contents col">
          <div class="col">
            <h2 style="color: rgb(30, 30, 30) ;">徐 唯毓</h2>
            <div class="post-meta">
            </div>
          </div>

          <hr style="margin: 10px 0;">
          <div class="col">
            <span class="d-block">國立台灣科技大學電子工程系 研究生</span>
          </div>
        </div>
      </div>
    </div>

  </div>
</div>
{% endblock %}

webui/templates/base.html
<!DOCTYPE html>
<html lang="zh-tw">

<head>
  {% block head %}
  <title>{% block title %}心臟斷層掃描影像分析{% endblock %}</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <link href="https://fonts.googleapis.com/css?family=B612+Mono|Cabin:400,700&display=swap" rel="stylesheet">

  <link href="{{ url_for('static', filename='css/bootstrap.min.css') }}" rel="stylesheet">
  <link href="{{ url_for('static', filename='css/jquery-ui.css') }}" rel="stylesheet">
  <link href="{{ url_for('static', filename='css/jquery.fancybox.min.css') }}" rel="stylesheet">
  <link href="{{ url_for('static', filename='css/aos.css') }}" rel="stylesheet">
  <link href="{{ url_for('static', filename='css/style.css') }}" rel="stylesheet">
  <link href="{{ url_for('static', filename='css/effect.css') }}" rel="stylesheet">
  {% endblock head %}
  
  <!-- loader -->
  {% block scripts %}
  <div id="loader" class="show fullscreen"><svg class="circular" width="48px" height="48px"><circle class="path-bg" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke="#eeeeee"/><circle class="path" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke-miterlimit="10" stroke="#ff5e15"/></svg></div>
  <script src="{{ url_for('static', filename='js/jquery-3.3.1.min.js') }}"></script>
  <script src="{{ url_for('static', filename='js/jquery-migrate-3.0.1.min.js') }}"></script>
  <script src="{{ url_for('static', filename='js/jquery-ui.js') }}"></script>
  <script src="{{ url_for('static', filename='js/popper.min.js') }}"></script>
  <script src="{{ url_for('static', filename='js/bootstrap.min.js') }}"></script>
  <script src="{{ url_for('static', filename='js/jquery.stellar.min.js') }}"></script>
  <script src="{{ url_for('static', filename='js/jquery.countdown.min.js') }}"></script>
  <script src="{{ url_for('static', filename='js/jquery.easing.1.3.js') }}"></script>
  <script src="{{ url_for('static', filename='js/aos.js') }}"></script>
  <script src="{{ url_for('static', filename='js/jquery.fancybox.min.js') }}"></script>
  <script src="{{ url_for('static', filename='js/jquery.sticky.js') }}"></script>
  <script src="{{ url_for('static', filename='js/main.js') }}"></script>
  {% endblock %}
 {% block javascript %}{% endblock %}
</head>

<body data-spy="scroll" data-target=".site-navbar-target" data-offset="300">

  <!-- site-wrap -->
  <div class="site-wrap">

    <div class="site-mobile-menu site-navbar-target">
      <div class="site-mobile-menu-header">
        <div class="site-mobile-menu-close mt-3">
          <span class="icon-close2 js-menu-toggle"></span>
        </div>
      </div>
      <div class="site-mobile-menu-body"></div>
    </div>

    <div class="header-top">
      <div class="container">
        <div class="row align-items-center">
          <div class="col-12 col-lg-6 d-flex">
            <a href="{{ url_for('webui.index') }}" class="site-logo" style="font-weight: 500;color: rgb(50,50,50); letter-spacing: 1px;">
              心臟斷層掃描影像分析
            </a>
            <a href="#" class="ml-auto d-inline-block d-lg-none site-menu-toggle js-menu-toggle text-black"><span
                class="icon-menu h3"></span></a>
          </div>
          
          <div class="col-6 d-block d-lg-none text-right">
            
          </div>
        </div>
      </div>

      <div class="site-navbar py-2 js-sticky-header site-navbar-target d-none pl-0 d-lg-block" role="banner">

      <div class="container">
        <div class="d-flex align-items-center">
          
          <div class="mr-auto">
            <nav class="site-navigation position-relative text-right" role="navigation">
              <ul class="site-menu main-menu js-clone-nav mr-auto d-none pl-0 d-lg-block">
                <li class="active">
                  <a href="{{ url_for('webui.index') }}" class="nav-link text-left borderCenter">主頁</a>
                </li>
                <li>
                  <a href="{{ url_for('webui.about') }}" class="nav-link text-left borderCenter">關於</a>
                </li>
              </ul>                                                                                                                                                                                                                                                                                         
            </nav>

          </div>
         
        </div>
      </div>

    </div>
    <hr>
    <div class="site-section" style="padding:1em 0;">
    </div>

    <!-- page Content -->
    {% block content %}{% endblock %}

    <!-- footer -->
    <div class="footer">
      <div class="container">
        

        <div class="row">
          <div class="col-12">
            <div class="copyright">
                <p>
                  <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                  Copyright &copy;<script>document.write(new Date().getFullYear());</script> MITLAB. All rights reserved.
                  <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                </p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

</body>

</html>

webui/templates/cxr.html
{% extends 'base.html' %}

{% block content %}
<div class="py-0">
  <div class="container">
    <div class="half-post-entry d-block d-lg-flex bg-light">
      <div class="contents col">
        <span class="caption">Prediction</span>
        <h2 style="color:rgb(20, 20, 20)">CXR 中風預測</h2>
        <p class="mb-3">根據胸部X光的影像，判斷病人中風的可能性</p>
      </div>
    </div>
    {% include '_step.html' %}
  </div>
</div>
{% include '_site-section_cxr.html' %}
{% endblock %}

webui/templates/error.html
{% extends "base.html" %}

{% block content %}
<div class="py-0">
  <div class="container">
    <div class="half-post-entry d-block d-lg-flex bg-light">
      <div class="contents col">
        <span class="caption">{{ error[0] }}</span>
        <h2 style="color:rgb(20, 20, 20)">{{ error[1] }}</h2>
        <p class="mb-3"><a href="{{ url_for('webui.index') }}">Go Back</a></p>
      </div>
    </div>
  </div>
</div>
{% endblock %}